name: MacOS (with Clang)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install make
        run: brew install make
      - name: Configure CMake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug  ..
      - name: Build executable
        working-directory: ./build
        run: make neblina neblina-tests
      - name: Run tests
        working-directory: ./build
        run: ./neblina-tests
